services:
  - docker

before_script:
 - ./scripts/write_envs_to_file.sh
 - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --build -d
 - ./scripts/wait_for_backend.sh

script:
 - bash scripts/check_website_availability.sh
 - docker-compose -f docker-compose.yml -f docker-compose.prod.yml exec backend python3 manage.py test

after_script:
 - docker-compose -f docker-compose.yml -f docker-compose.prod.yml logs
 - docker-compose -f docker-compose.yml -f docker-compose.prod.yml down
