version: '3.7'

services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/match4everyone-backend'
      - backend.dev.env  
    ports:
      - '8000:8000'
    tty: true # needed for error output during django startup
    restart: always 
    environment:
      - CI
      - TRAVIS
      - TRAVIS_PULL_REQUEST_SLUG
