version: '3.7'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - CI
      - TRAVIS
      - TRAVIS_PULL_REQUEST_SLUG
