version: '3.7'

services:

  backend:
    volumes:
      - backend-run:/backend/run
    ports:
      - '80:8000'
    networks:
      - network
    env_file:
      - backend.prod.env
      - database.prod.env
    environment:
     - DJANGO_SETTINGS_MODULE=match4everyone.settings.production
     - PRODUCTION=True
    command: gunicorn -c /backend/gunicorn.conf.py match4everyone.wsgi
    depends_on:
      - database


  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
     - db-data:/var/lib/postgresql/data
     - db-backup:/backups/
    restart: always
    env_file:
     - database.prod.env
    expose:
     -  5432
    networks:
     - network
    command: postgres -c config_file=/etc/postgresql.conf

networks:
 network:

volumes:
  db-data:
  db-backup:
