version: '3.7'

services:
    backend:
        env_file:
            - backend.dev.env
        volumes:
            - './frontend:/frontend'

    frontend:
        entrypoint: [ "npm" , "run", "dev" ]
        volumes:
            - './frontend/src:/frontend/src'
            - './frontend/dist:/frontend/dist'
