version: '3.7'

services:
    backend:
        volumes:
            - './frontend:/frontend'

    frontend:
        entrypoint: [ "npm" , "run", "dev" ]
        volumes:
            - './frontend/src:/frontend/src'
            - './frontend/dist:/frontend/dist'
