version: '3.7'

services:

  backend:
    ports:
      - '80:8000'
    networks:
      - network
    env_file:
      - backend.prod.env
      - database.prod.env
    environment:
     - DJANGO_SETTINGS_MODULE=match4everyone.settings.production
     - PRODUCTION=True
    user: ${BACKEND_USER:-0}
    command: gunicorn -c /match4everyone-backend/gunicorn.conf.py match4everyone.wsgi
    depends_on:
      - database


  database:
    image: postgres:12
    volumes:
     - ./database/data:/var/lib/postgresql/data
     - ./database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
     - ./database/postgresql.conf:/etc/postgresql.conf
     - ./database/backups:/backups/
    restart: always
    env_file:
     - database.prod.env
    expose:
     -  5432
    networks:
     - network
    command: postgres -c config_file=/etc/postgresql.conf

networks:
 network:

#volumes:
#  postgres-data:
