version: '3.7'

services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/match4everyone-backend'
      - './frontend:/frontend'
    env_file:
      - backend.dev.env  
    ports:
      - '8000:8000'
    tty: true # needed for error output during django startup
    restart: always
    environment:
      - CI
      - TRAVIS
      - TRAVIS_PULL_REQUEST_SLUG

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend/src:/app/src'
      - './frontend/dist:/app/dist'      
    entrypoint: [ "npm" , "run", "dev" ]

