version: '3.7'

services:

  backend:
    volumes:
      - './backend:/match4everyone-backend'
      - 'frontend-bundles:/frontend/dist'
    ports:
      - '80:8000'
    networks:
      - network
    env_file:
      - backend.prod.env
      - database.prod.env
    environment:
     - DJANGO_SETTINGS_MODULE=match4everyone.settings.production
    user: ${CURRENT_UID:-0}
    command: bash -c 'while ! (< /dev/tcp/database/5432) &> /dev/null; do echo "Waiting for database..."; sleep 1; done; gunicorn -c /match4everyone-backend/gunicorn.conf.py match4everyone.wsgi'
    depends_on:
      - database

  frontend:
    volumes:
      - 'frontend-bundles:/app/dist'

  database:
    image: postgres:12
    volumes:
     - ./database/data:/var/lib/postgresql/data
     - ./database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
     - ./database/postgresql.conf:/etc/postgresql.conf
     - ./database/backups:/backups/
    restart: always
    env_file:
     - database.prod.env
    expose:
     -  5432
    networks:
     - network
    command: postgres -c config_file=/etc/postgresql.conf

networks:
 network:

volumes:
  frontend-bundles:
